### PR TITLE
Add pipeline support

### PR DESCRIPTION
**Pull request by basil**
This change modernizes the log file size checker plugin and adds support for pipeline jobs. This is my first attempt at submitting a pull request to this plugin, so please let me know if there's anything different I should be doing.

I started by cleaning up the POM: updating the parent POM version, bumping the minimum Jenkins version to something more modern, and modernizing various other parts of the POM in accordance with the POM that gets generated from the latest archetype. I also removed various POM configuration settings that duplicate settings in the parent POM.

The plugin changes should be fairly straightforward. I made the class extend `SimpleBuildWrapper` and followed the relevant instructions in [the documentation](http://javadoc.jenkins-ci.org/jenkins/tasks/SimpleBuildWrapper.html). I also implemented a small optimization: we're no longer starting the log size timer task unless we need to (previously, we were starting it unconditionally). The only change that might not be obvious is the removal of the "Executor:" log statement; I did this to pacify FindBugs, which was complaining about a potential `NullPointerException`.

I updated the tests to use the new `JenkinsRule` infrastructure. I also restructured things slightly with regard to the test data; previously the job came from an XML configuration file in the `LogfilesizecheckerWrapperIntegrationTest.zip`; I've pulled this out into the Java code for the test so it is easier to edit. The test data file now just contains the `lorem2100kB` files used for the `freestyle` and `pipeline` jobs in the tests. I also fixed a small bug in `test5`, which was not properly cleaning up after itself and affecting future tests. My `test6`, `test7`, `test8`, `test9`, and `test10` tests are straightforward ports to pipeline of the original `test1`, `test2`, `test3`, `test4`, and `test5` tests. All tests pass:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running hudson.plugins.logfilesizechecker.LogfilesizecheckerWrapperIntegrationTest
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 58.446 s - in hudson.plugins.logfilesizechecker.LogfilesizecheckerWrapperIntegrationTest
[INFO] Running InjectedTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.947 s - in InjectedTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 21, Failures: 0, Errors: 0, Skipped: 0
[...]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:37 min
[INFO] Finished at: 2017-11-30T18:29:33-08:00
[INFO] Final Memory: 76M/860M
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by stefanbrausch** [comment]
Thanks for your pull request.
Check is in progress.

**Comment by Jochen-A-Fuerbacher** [comment]
Thanks!

**Comment by pgnunes** [comment]
"Issues" is not enabled for this project so I'm reporting an issue here...
The plugin (v1.3) is not working for pipeline jobs (apparently only for freestyle jobs).
Tested on (an old version) Jenkins Cloudbees 2.7.21 with Pipeline plugin 2.4.
Thanks

**Comment by stefanbrausch** [comment]
@pgnunes Please open an issue here: https://issues.jenkins-ci.org/ with component logfilesizechecker-plugin
Thanks

**Pull request merged**
