### PR TITLE
Get tests working on Windows

### PR DESCRIPTION
**Pull request by basil**
This change attempts to get the tests working on Windows. Note that I don't actually have access to a Windows box, so I'll be attempting to use the tests that get kicked off from the PR on `ci.jenkins.io` to determine the success of this change.

As a bonus, I also updated the plugin POM to the latest versoin.

### CODE REVIEW

**Comment by basil** [comment]
> Note that I don't actually have access to a Windows box, so I'll be attempting to use the tests that get kicked off from the PR on ci.jenkins.io to determine the success of this change.

Well, looks like that plan [isn't working out too well right now](https://ci.jenkins.io/job/Plugins/job/logfilesizechecker-plugin/job/PR-6/1/consoleFull):

```
19:28:10 [windows] Still waiting to schedule task
19:28:10 [windows] All nodes of label ‘windows’ are offline
```

**Comment by basil** [comment]
Looks like the test eventually ran. Tests 1, 2, and 5 failed, but the rest passed -- not bad for a shot in the dark! Looking at the failures, it looks like the plugin failed to kick in and mark the build with a non-success status in time. My first thought is that the one-second sleep in the test isn't long enough to allow the plugin to kick in. I'll change it to a three-second sleep and see if that makes a difference.

**Comment by basil** [comment]
Looks like that did the trick! @stefanbrausch @Jochen-A-Fuerbacher I think this is ready for review now. This should also get the build status button in the `README` to show that the build is passing.

**Comment by Jochen-A-Fuerbacher** [comment]
Thanks, @basil !

**Pull request merged**
